// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS5ceHb0eajv6LG0yiYJeYS7z3wfk--cQ',
    appId: '1:386665558674:web:8a5032b789f43b7ecdec4b',
    messagingSenderId: '386665558674',
    projectId: 'demologin-7b582',
    authDomain: 'demologin-7b582.firebaseapp.com',
    storageBucket: 'demologin-7b582.firebasestorage.app',
    measurementId: 'G-06844N07ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwIq0JsguJp63y1MC83g0r8k2s8RKo1X8',
    appId: '1:386665558674:android:6999fa0736726d45cdec4b',
    messagingSenderId: '386665558674',
    projectId: 'demologin-7b582',
    storageBucket: 'demologin-7b582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeCW2-cnxljd3tlwMF9PVBz_oby4TLXN4',
    appId: '1:386665558674:ios:f41d78cf3a2bfd58cdec4b',
    messagingSenderId: '386665558674',
    projectId: 'demologin-7b582',
    storageBucket: 'demologin-7b582.firebasestorage.app',
    iosBundleId: 'com.example.phamleanhkhoa6451071035Btlt9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeCW2-cnxljd3tlwMF9PVBz_oby4TLXN4',
    appId: '1:386665558674:ios:f41d78cf3a2bfd58cdec4b',
    messagingSenderId: '386665558674',
    projectId: 'demologin-7b582',
    storageBucket: 'demologin-7b582.firebasestorage.app',
    iosBundleId: 'com.example.phamleanhkhoa6451071035Btlt9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS5ceHb0eajv6LG0yiYJeYS7z3wfk--cQ',
    appId: '1:386665558674:web:c099562d1974f3decdec4b',
    messagingSenderId: '386665558674',
    projectId: 'demologin-7b582',
    authDomain: 'demologin-7b582.firebaseapp.com',
    storageBucket: 'demologin-7b582.firebasestorage.app',
    measurementId: 'G-H33H7JVJYK',
  );
}
